### DISCUSSION TITLE
ICantBelieveItsNotValetudo use with Valetudo RE?

### DISCUSSION THREAD

**Discussion by ottelo9** [Poeschl/Hassio-Addons#212] [Q&A] [answered]
Hi there. Thanks for your work!

I use Valetudo RE and HA on my Rpi (Hassio). I installed your addon and configured it. But how to add the map to the UI?

my log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-config: executing... 
[08:54:58] INFO: Setup config
[cont-init.d] setup-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:54:58] INFO: Start ICantBelieveItsNotValetudo
> i-cant-believe-its-not-valetudo@2021.2.1 start /app
> node app.js
Loading configuration file: /app/config.json
Connecting to MQTT broker...
Connected to MQTT broker.
Skipping map generation as it has not changed.
Skipping map generation as it has not changed.
Skipping map generation as it has not changed.
Skipping map generation as it has not changed.
```

My config:
I changed the **broker_url** and **mapDataTopic**

```
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  scale: 4
  rotate: 0
mapColors:
  floor: '#0076ff'
  obstacle: '#52aeff'
  path: '#ffffff'
mqtt:
  identifier: rockrobo
  topicPrefix: valetudo
  autoconfPrefix: homeassistant
  broker_url: 'mqtt://mqtt:mqtt@core-mosquitto'
  caPath: ''
  mapDataTopic: valetudo/rockrobo/map
  minMillisecondsBetweenMapUpdates: 10000
  publishMapImage: true
```
