### DISCUSSION TITLE
Mopidy start playlist in home assistant action

### DISCUSSION THREAD

**Discussion by JayNutZ** [Poeschl/Hassio-Addons#321] [Q&A]
The setup works fine for TTS and specific sound files, using the `media_player.play_media` service:

```
service: media_player.play_media
data:
  media_content_id: file:///media/mopidy/media/alarm-ice.mp3
  media_content_type: music
target:
  entity_id: media_player.mpd
```

But for playlists i'm currently unable to make it work. I have a `.m3u8` playlist generated by the web ui of the plugin. I've tried copying the file from the mopidy playlist directory to the media folder, using the `file:///`-syntax as it is used for mp3 files, as the `m3u:Chill.m3u8`-URI you get from the web interface context menu. Just to be sure i also tested setting the `media_content_type` to back to music, because it works for a music file.
My expectation is, that i can use the `media_player.play_media` service aswell, making slight adjustments:

```
service: media_player.play_media
data:
  media_content_id: file:///media/mopidy/playlists/chill.m3u8
  media_content_type: playlist
target:
  entity_id: media_player.mpd
```

Otherwise, it's a charme to have this add-on on hand. I hope i can get this last thing to work 🤩
