### ISSUE TITLE
[Valetudo-mapper] can't save config on 1.7.1

### ISSUE THREAD

**Issue by kotarokun** [Poeschl/Hassio-Addons#184]
**Which addon?**
it is for Valetudo-mapper

**Describe the bug**
i can't save my settings vor Valetudo-Mapper...

**To Reproduce**
I just change the IP of mqtt, and use the rest from standard-Settings..
like here: 
```
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  drawCurrentlyCleanedZones: false
  drawCurrentlyCleanedBlocks: false
  drawForbiddenZones: true
  drawVirtualWalls: true
  scale: 4
  gradientBackground: true
  autoCrop: 20
mapColors: {}
mqtt:
  identifier: rockrobo
  topicPrefix: valetudo
  autoconfPrefix: homeassistant
  broker_url: 'mqtt://192.168.***.**:1883'
  caPath: ''
  mapDataTopic: valetudo/rockrobo/map_data
  minMillisecondsBetweenMapUpdates: 10000
  publishMapImage: true
  publishMapData: false
```

and get these error: `Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'mapSettings': {'drawPath': True, 'drawCharger': True, 'drawRobot': True, 'drawCurrentlyCleanedZones': False, 'drawCurrentlyCleanedBlocks': False, 'drawForbiddenZones': True, 'drawVirtualWalls': True, 'scale': 4, 'gradientBackground': True, 'autoCrop': 20}, 'mapColors': {}, 'mqtt': {'identifier': 'rockrobo', 'topicPrefix': 'valetudo', 'autoconfPrefix': 'homeassistant', 'broker_url': 'mqtt://192.168.***.**:1883', 'caPath': '', 'mapDataTopic': 'valetudo/rockrobo/map_data', 'minMillisecondsBetw...`

**System**

* Supervisor version: Version 2021.02.9
* Host system version:  core-2021.2.3
