### ISSUE TITLE
Syntax Error with Valetudo 2021_02

### ISSUE THREAD

**Issue by Kugelfang666** [Poeschl/Hassio-Addons#187]
**Which addon?**

 I canotbeliefe its not Valetudo
**Describe the bug**

After installing valetudo 2021_02 on my machine your add-on struggles with my setup: I'm getting the following error message:

`SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:86:42)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:410:12)
    at work (/app/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
`

<img width="969" alt="Screenshot" src="https://user-images.githubusercontent.com/3289654/108216970-551a7480-7133-11eb-8978-839cb10cf9ab.png">

**To Reproduce**
Configuration of the add-on

```
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  scale: 4
  rotate: 0
mapColors:
  floor: '#0076ff'
  obstacle_weak: '#6699ff'
  obstacle_strong: '#52aeff'
  path: '#ffffff'
mqtt:
  identifier: robot
  topicPrefix: valetudo
  autoconfPrefix: homeassistant
  broker_url: '!secret mqtt_valetudo_map_url'
  caPath: ''
  mapDataTopic: valetudo/robot/map_data
  minMillisecondsBetweenMapUpdates: 10000
  publishMapImage: true
```

**Expected behavior**

**Screenshots**

**System**

* Supervisor version:  2021.02.9
* Host system version: 
 core-2021.2.3
