### ISSUE TITLE
Error when detecting secrets in repo: `grep: Unmatched [, [^, [:, [., or [=`

### ISSUE THREAD

**Issue by fliphess** [Poeschl/Hassio-Addons#243]
He Markus, 

To start: Thanks a lot for this plugin, it is exactly what I was looking for :) 

I ran into some issues, and I think this is not that easy to solve in another way than document the behaviour as a known issue.
For future reference I decided to make an issue to ensure other's can solve this a bit more quickly than I did 👍 

**Which addon?**
git-exporter

**Describe the bug**
When secrets contain characters that are used in regexes, (in my case a `[`) the backup fails with a grep error. 
When I start the git-exporter addon, using the latest version of the plugin, I get a grep error, caused by what it seems is an incorrect 
regex:
```
[16:05:58] INFO: Prohibited patterns:
password:\s?[\'"]?\w+[\'"]?\n?
token:\s?[\'"]?\w+[\'"]?\n?
client_id:\s?[\'"]?\w+[\'"]?\n?
api_key:\s?[\'"]?\w+[\'"]?\n?
chat_id:\s?[\'"]?\w+[\'"]?\n?
allowed_chat_ids:\s?[\'"]?\w+[\'"]?\n?
latitude:\s?[\'"]?\w+[\'"]?\n?
longitude:\s?[\'"]?\w+[\'"]?\n?
credential_secret:\s?[\'"]?\w+[\'"]?\n?
([0-9]{1,3}\.){3}[0-9]{1,3}
([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})
[16:05:58] INFO: Checking for secrets
grep: Unmatched [, [^, [:, [., or [=
[16:05:58] ERROR: Found secrets in files!!! Fix them to be able to commit!
```

(Especially the grep error: `grep: Unmatched [, [^, [:, [., or [=`)

**To Reproduce**
1. Install the addon
2.  Used config: 
```
repository:
  url: '!secret git_exporter_url'
  username: '!secret git_exporter_username'
  password: '!secret git_exporter_password'
  pull_before_push: true
  commit_message: Home Assistant Git Exporter
export:
  lovelace: true
  addons: true
  esphome: true
  node_red: false
check:
  enabled: true
  check_for_secrets: true
  check_for_ips: true
exclude:
  - '*.db'
  - '*.log'
  - __pycache__
  - ._*
  - .DS_Store
  - deps
  - known_devices.yaml
  - tts
  - www
  - appdaemon
  - zigbee2mqtt
dry_run: false
```

Using a secret in `secrets.yaml` with special chars in it: 
```
some_secret: "jrknvs[ankjaregsk$`"
```

The plugin crashes with the grep error mentioned secrets, rather than invalid chars in secret error.

**Expected behavior**
The plugin makes a backup as my config is clean 
Or as an alternative: It is documented that special chars (that have a special meaning in regexes) cannot be used as in passwords when using this plugin.

**Workaround:**
Remove all special chars from your passwords and secrets. 

If preferred I can make a PR to mention this in the docs, so don't hesitate to bounce the issue right back at me :)
