### ISSUE TITLE
[Gitea Eporter] URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by thundergreen** [Poeschl/Hassio-Addons#249]
**Which addon?**

Gitea Exporter
**Describe the bug**

Getting error:

```URL using bad/illegal format or missing URL```

**To Reproduce**

my config:

```
repository:
  url: https://gitea.ddns.net/thundergreen/home-assistant/
  username: thu*****en@gmail.com
  password: N******1!  
  pull_before_push: false
  commit_message: Home Assistant Config Upload
export:
  lovelace: true
  addons: true
  esphome: true
  node_red: true
check:
  enabled: false
  check_for_secrets: true
  check_for_ips: true
exclude:
  - '*.db'
  - '*.log'
  - __pycache__
  - ._*
  - .DS_Store
  - deps/
  - known_devices.yaml
  - tts/
  - www/images
dry_run: false
```
