### ISSUE TITLE
Picotts speaks template verbally

### ISSUE THREAD

**Issue by emacsLover** [Poeschl/Hassio-Addons#29]
**picotts_remote**

**Describe the bug**
Pico speaks verbally the template text *left curly bracket left curly bracket states..* instead of the data value *cloudy*

**To Reproduce**
1. Go to Services
2. Click on tts.picotts_remote_say
3. Input yaml > message: “{{ states(‘sensor.weather.home’) }}”
4. Call service

**Expected behavior**
Pico speaks the state e.g. "cloudy"

**Comment by Poeschl** [comment]
To get the sensors values use `data_templates`.
To get an idea: https://community.home-assistant.io/t/google-text-to-speech-data-vs-data-template/46134

Or take a look at the docs [here](https://www.home-assistant.io/docs/configuration/templating/)

**Comment by emacsLover** [comment]
Thank you for taking your time. I've read through your suggestions. Maybe you
see what I'm missing?


**To Reproduce**
Steps to reproduce the behavior:
1. Go to Services
2. Click on tts.picotts_remote_say
3. Input yaml >

data_template:
message: >
 {{ states(‘sensor.shopping_list’) }}
 
Error: Extra Keys not allowed 

Steps to reproduce the behavior:
1. Go to Services
2. Click on tts.picotts_remote_say
3. Input yaml >

message: {{states('sensor.shopping_list')}}

Problem remains...speaks verbally

**Comment by Poeschl** [comment]
I assume that data_templates are not supported on the service view.
Maybe try to create a script for testing. It could look like this:

```
scripts:
  - test:
    sequence:
      - service: tts.picotts_remote_say
        data_template:
          message: {{ states(‘sensor.shopping_list’) }}
```
[More about scripts] (https://www.home-assistant.io/integrations/script/)

**Comment by emacsLover** [comment]
:+1:  Thank you so much Markus :1st_place_medal: 

```
script:
  message_temperature:
    sequence:
      # This is Home Assistant Script Syntax
      - service: tts.picotts_remote_say
        data_template:
          message: Current temperature is {{ states('sensor.shopping_list') }}
```
