### ISSUE TITLE
Using a USB sound card input as an input to MPD

### ISSUE THREAD

**Issue by mikey60** [Poeschl/Hassio-Addons#297]
**Which addon?**
mpd

**Is your feature request related to a problem? Please describe.**
I have a USB sound board connected to my Raspberry Pi that is identified in your configuration:
![image](https://user-images.githubusercontent.com/2157038/152020703-9fe4bd7a-6c98-43bf-a2e1-380bc6d178e8.png)
I would like to be able to specify the audio input as an input to MPD.  I am able to do this in home-assistant core.  An example script I use in the core version is:
```
test_music:
  alias: Test Music
  sequence:
  - service: media_player.play_media
    data:
      media_content_id: analog_input
      media_content_type: playlist
    target:
      entity_id: media_player.mpd
  mode: single
``` 
where the playlist file, analog_input.m3u is:
```
#EXTM3U
alsa://hw:1,0
```
The USB sound card input is shown as Card 1, Device 0 when entering the command arecord -l  in the host system and when executing the command in a bash terminal for the docker hassio_audio container
The same thing can be done on the command line as:
mpc add alsa://hw:1,0; mpc play in the host system but not in the hassio supervised container version of mpd.  The error is:
```
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
exception: Failed to decode alsa://hw:1,0; Failed to open device: hw:1,0 (No such file or directory)
player: played "alsa://hw:1,0"
exception: No such directory
```

**Describe the solution you'd like**
I would like to be able to connect the USB sound card input as a mpd input in the mpd addon like I can using Home-assistant core. But maybe this is actually a deficiency with the docker hassio-audio container.

**Describe alternatives you've considered**
I would continue to use Home-assistant core version, but it would be nice to switch to the hassio supervised container so I don't have to continually fight with upgrades

**Additional context**
