### ISSUE TITLE
rsync - Documentation is out of date

### ISSUE THREAD

**Issue by Crocmagnon** [Poeschl/Hassio-Addons#343]
**Which addon?**
rsync

**Describe the bug**
The documentation is out of date. The changelog for version 1.5.0 on 2022-08-15 states that "⚠️ Breaking Change ⚠️ Your addon config needs to be changed to the new per-folder options and destinations."

The documentation hasn't been changed in two years, I don't know how to "change my config to the new per-folder options".

**To Reproduce**
1. Install the latest version
2. Configure as the Documentation tab instructs you to.
3. Start the addon

Sample config:
```yaml
private_key_file: /ssl/rsync/id_rsa
username: gaugendre
folders:
  - /backup/
remote_host: 192.168.0.6
remote_folder: /mnt/data/backups/hass
remote_port: 22
options: "--links --times --recursive --prune-empty-dirs --delete"
```

**Expected behavior**
The documentation should provide up to date instructions and the configuration tab should be updated to reflect any change in the properties type to avoid having to edit YAML.

**System**

* Supervisor version: 2022.08.5
* Host system version: Operating System 8.5
