### ISSUE TITLE
rsync - parse error: Unfinished string at EOF at line 2, column 0

### ISSUE THREAD

**Issue by Crocmagnon** [Poeschl/Hassio-Addons#344]
**Which addon?**
rsync

**Describe the bug**
I'm trying to sync my HA backups to a remote server. I had everything setup properly and working smoothly before release 1.5.0 and the config breaking change (#343). I've now updated my config, but I'm getting the following error in the logs of the addon:

```plain
[08:38:37] INFO: Use private key from /ssl/rsync/id_rsa
[08:38:38] INFO: Use port 38303
parse error: Unfinished string at EOF at line 2, column 0
```

The addon keeps running but the CPU and RAM usages are at 0%. Sync doesn't happen.

**To Reproduce**
1. Install latest addon version
2. Configure the addon
3. Start the addon
4. View the logs

Sample config:
```yaml
private_key_file: /ssl/rsync/id_rsa
username: gaugendre
folders:
  - source: /backup/
    options: "--links --times --recursive --prune-empty-dirs --delete"
    destination: /mnt/data/backups/hass
remote_host: 192.168.0.6
remote_port: 22
```

**Expected behavior**
The addon shouldn't display this error in the logs and sync should happen properly

**System**
* Supervisor version: 2022.08.5
* Host system version: Operating System 8.5
