### ISSUE TITLE
custom_secrets: unbound variable

### ISSUE THREAD

**Issue by lgwapnitsky** [Poeschl/Hassio-Addons#361]
**Which addon?**
Git Exporter

**Describe the bug**
When running Git Exporter with check_for_secrets: false, I receive the following error:

```
/run.sh: line 98: custom_secrets: unbound variable
```

Set configuration as follows:

```
  pull_before_push: true
  commit_message: Home Assistant Git Exporter
  branch_name: master
export:
  lovelace: true
  addons: true
  esphome: true
  node_red: true
check:
  enabled: true
  check_for_secrets: false
  check_for_ips: true
exclude:
  - "*.db"
  - "*.log*"
  - __pycache__
  - ._*
  - .DS_Store
  - deps/
  - known_devices.yaml
  - tts/
  - "*.db-shm"
  - "*.db-wal"
  - "*.gz"
secrets: []
allowed_secrets: []
dry_run: false
```

(repo information removed for security)

**Expected behavior**
Git upload should work

**System**
Home Assistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest
