### ISSUE TITLE
make default folder persistent

### ISSUE THREAD

**Issue by tomaszduda23** [Poeschl/Hassio-Addons#447]
**Which addon?**
syncthing

**Is your feature request related to a problem? Please describe.**
If container is restarted default data are lost. It is easy to miss during configuration.

**Describe the solution you'd like**
It would be nice if default folder would be placed inside addon's persistent date. It could be done by setting `HOME` env vaialb.e

**Additional context**

You could also set STNODEFAULTFOLDER to prevent creating default sync directory.

My example config looked like this.
```
    env:
      - name: STNODEFAULTFOLDER
        value: "1"
      - name: HOME
        value: "/var/syncthing-data/"
```
