### ISSUE TITLE
[Valetudo-Mapper] Config issues

### ISSUE THREAD

**Issue by thundergreen** [Poeschl/Hassio-Addons#45]
**Which addon?**

Valeturo Mapper
**Describe the bug**

Hassio Addon won't take into account config options
**To Reproduce**

**Expected behavior**

**Screenshots**

20-02-08 14:07:06 WARNING (MainThread) [hassio.addons.validate] Unknown options gradientBackground
20-02-08 14:07:06 WARNING (MainThread) [hassio.addons.validate] Unknown options drawForbiddenZones
20-02-08 14:07:06 WARNING (MainThread) [hassio.addons.validate] Unknown options drawVirtualWalls

my config:

```
identifier: rockrobo
topicPrefix: valetudo
autoconfPrefix: homeassistant
broker_url: 'mqtt://hass:hass@192.168.1.41'
caPath: ''
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  gradientBackground: false
  drawForbiddenZones: true
  drawVirtualWalls: true
  border: 2
  scale: 4
mapDataTopic: valetudo/rockrobo/map_data
minMillisecondsBetweenMapUpdates: 10000
publishMapImage: true
publishMapData: true
```

This is the original config from rand256

```
{
        "mqtt" : {
            "identifier": "rockrobo",
            "topicPrefix": "valetudo",
            "autoconfPrefix": "homeassistant",
            "broker_url": "mqtt://user:pass@example.com:port",
            "caPath": "",
            "mapSettings": {
                "drawPath": true,
                "drawCharger": true,
                "drawRobot": true,
                "drawForbiddenZones": true,
                "drawVirtualWalls": true,
                "border": 2,
                "scale": 4,
                "gradientBackground": true,
                "crop_x1": 30,
                "crop_y1": 70,
                "crop_x2": 440,
                "crop_y2": 440
            },
            "mapDataTopic": "valetudo/rockrobo/map_data",
            "minMillisecondsBetweenMapUpdates": 10000,
            "publishMapImage": true,
            "publishMapData": false
        },
        "webserver": {
            "enabled": false,
            "port": 3000
        }
}
```
