### ISSUE TITLE
ICantBelieveItsNotValetudo - SyntaxError: Unexpected token in JSON

### ISSUE THREAD

**Issue by HITChris** [Poeschl/Hassio-Addons#83]
**Which addon?**
ICantBelieveItsNotValetudo addon v. 2.1.0

**Describe the bug**
Upon configuring and then running the addon, the following container error is logged:

```
Loading configuration file: /app/config.json
Connecting to MQTT Broker
Webserver running on port 3000
Connected to MQTT Broker
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:80:42)
    at MqttClient.emit (events.js:223:5)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:336:12)
    at work (/app/node_modules/mqtt/lib/client.js:292:12)
    at processTicksAndRejections (internal/process/task_queues.js:76:11
```

Addon config:

```
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  scale: 4
mapColors: {}
mqtt:
  enabled: true
  identifier: roborock
  topicPrefix: valetudo
  autoconfPrefix: homeassistant
  broker_url: 'mqtt://user:pass@mqtthost'
  caPath: ''
  mapDataTopic: valetudo/roborock/map_data
  minMillisecondsBetweenMapUpdates: 10000
  publishMapImage: true
```

Relevant valetudo /mnt/data/val*/conf*:

```
  "mqtt": {
    "enabled": false,
    "identifier": "roborock",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://user:pass@mqtthost",
    "provideMapData": true,
    "caPath": "",
    "qos": 0
  },
```

No image is pulled into the auto-generated mqtt camera. This appears to be the same issue reported by another user of this addon in https://github.com/rand256/valetudo/issues/150. Your valetudo-mapper addon works without issue.

**To Reproduce**
1. Install addon ICantBelieveItsNotValetudo v 2.1.0
2. Click on Start
3. Review Logs

**System**

* Vacuum: Gen2 on Valetudo RE 0.9.4
* Supervisor version: 224
* Install: Home Assistant Supervised 0.110.1
