### ISSUE TITLE
ICBINValetudo: TypeError: Cannot read property 'dimensions' of undefined [Valetudo 0.6.0 not yet supported]

### ISSUE THREAD

**Issue by elektrikfisch** [Poeschl/Hassio-Addons#92]
Hello! I've never played around with MQTT before, so I apologize if this is a simple configuration error on my part. I can confirm, however, that HASS is successfully communicating with Valetudo over MQTT, and it appears that ICBINV is successfully connecting to my MQTT broker (core-mosquitto). However, the map will not load in the interface, and I see the following in the logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:05:04] INFO: Setup config
[23:05:04] INFO: Start ICantVelieveItsNotValetudo
> i-cant-believe-its-not-valetudo@0.2.0 start /app
> node app.js
Loading configuration file: /app/config.json
Connecting to MQTT Broker
Webserver running on port 3000
Connected to MQTT Broker
TypeError: Cannot read property 'dimensions' of undefined
    at Object.DRAW_MAP_PNG (/app/lib/Tools.js:69:72)
    at MqttClient.updateMapTopic (/app/lib/MqttClient.js:97:19)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:80:22)
    at MqttClient.emit (events.js:223:5)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:336:12)
    at work (/app/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:417:5)
TypeError: Cannot read property 'dimensions' of undefined
    at Object.DRAW_MAP_PNG (/app/lib/Tools.js:69:72)
    at MqttClient.updateMapTopic (/app/lib/MqttClient.js:97:19)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:80:22)
    at MqttClient.emit (events.js:223:5)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:336:12)
    at work (/app/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:417:5)
```

The TypeError block just repeats indefinitely about every five seconds.

It should be noted that I could not get ICBINV to connect using the standard core_mosquitto broker_url. I tried every combination of core_mosquitto, core-mosquitto, with and without quotes that I could think of. Should it just be ```broker_url: core_mosquitto```? Why wouldn't that work?

Here's my current config:
```
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  scale: 4
mapColors: {}
mqtt:
  identifier: rockrobo
  topicPrefix: valetudo
  autoconfPrefix: homeassistant
  broker_url: 'mqtt://valetudomap:password@192.168.3.101'
  caPath: ''
  mapDataTopic: valetudo/rockrobo/map_data
  minMillisecondsBetweenMapUpdates: 10000
  publishMapImage: true
```
